### ISSUE TITLE
Solr 5.x Build

### ISSUE THREAD

**Issue by mubaldino** [OpenSextant/Xponents#14]
SolrTextTagger is now on 2.2 with Solr 5.5 as max.  Some limitations in going to Solr 6.0 on STT v2.3-dev

Solr 4.10 is EOL, given Solr 6.0 is out.

**Comment by dsmiley** [comment]
Can you please file an issue to report the problem (if even you have no time to fix it at least we track it).

**Comment by mubaldino** [comment]
Obsoleted.  Xponents will skip compatibility tests with Solr 5.5; 
Will try Solr 6.4 next.
