### ISSUE TITLE
TaxonMatcher configure() called twice

### ISSUE THREAD

**Issue by gtjoumas** [OpenSextant/Xponents#52]
It appears that PlaceGeocoder is calling TaxonMatcher's configure method twice.

PlaceGeocoder lines:

299               personMatcher = new TaxonMatcher(); 
300               personMatcher.excludeTaxons("place."); /* but allow org., person., etc. */
301               personMatcher.configure();  

Instantiation of TaxonMatcher() calls configure().  This is called again on line 301 and results in the creation of 2 SolrProxies of which the 2nd process is not properly cleaned up on close.

**Comment by mubaldino** [comment]
will test immediately. thanks.

**Comment by mubaldino** [comment]
that tests out.  Patch will be in `3.3.5`
I don't have unit tests for that specifically, but it tests fine from my release testing.

**Comment by mubaldino** [comment]
thanks!
