### ISSUE TITLE
incorrect MGRS coordinate extracted

### ISSUE THREAD

**Issue by byburakyasar** [OpenSextant/Xponents#81]
Hello,
In a text that consists of invalid  MGRS coordinate Xcoord returns that invalid coordinate in a TextMatch list

For instance
xcoord.extract("37SCA211914648")  returns a list consists of GeoCoordMatch object with coord_text=37SCA2119014648

37SCA211914648 is an invalid coordinate but as it turns out that it is extracted incorrectly. Could you please have a look?

Thanks in advance.

**Comment by mubaldino** [comment]
@byburakyasar  - My apologies for not seeing this until now.

This was a behavior that was provided to rescue potential MGRs grids with typos.   It should throw an Exception or respect a runtime mode to allow such data rescue.   Background -- We had lots of customer data with typos in MGRS....  The current "rescue" of the coordinate is:

Grid: `37SCA` Northing/Easting: `211914648`  => yields two options where the 4 or 5 digit Northin/Easting may have a typo, two new MGRS coordinates are offered as possible interpretations:
- `21191`N, `46480`E
- `21190`N, `14648`E

A strict interpretation should be in play, I'd say.  With N/E offsets mismatched in length, then its possible the MGRS coordinate is not actually a coordinate.

Comment with any thoughts:  (a) what is the interpretation here if the MGRS coordinate had some possible typo?, (b) what is the API behavior desired?

thanks,
Marc

**Comment by byburakyasar** [comment]
@mubaldino in our case the returned coordinate caused a wrong display on the map since that coordinate was not valid. 

I understand the reason behind the rescue mechanism, it is good but it may be better to keep the interpreted coordinates and valid coordinates in separate TextMatch lists. Then we can decide what to do about the interpreted coordinates.

**Comment by mubaldino** [comment]
Implementation is in place for Xponents 3.6.  I'll add some comments after release
